name: Wrapper CI

on: [pull_request, push]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 1

    - name: Spell check everything
      uses: streetsidesoftware/cspell-action@v6
      with:
        root: .
        incremental_files_only: true
        config: .cspell.json
        verbose: true

    - name: Markdown lint
      uses: DavidAnson/markdownlint-cli2-action@v19
      with:
        config: .markdownlint.jsonc
        globs: |
          *.md
          **/*.md

  build_and_test:
    runs-on: ubuntu-latest
    env:
      NO_GPU: true
      DEBIAN_FRONTEND: noninteractive

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 1

    - name: Check formatting
      run: cargo fmt --check

    - name: Run Clippy linter
      run: cargo clippy --no-deps

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang libclang-dev

    - name: Build
      run: cargo build

    - name: Test
      run: cargo test --all-features
